var searchData=
[
  ['lagrange_1628',['Lagrange',['../classpython_1_1expansion_1_1Lagrange.html',1,'python::expansion']]],
  ['lagrangebasis_1629',['LagrangeBasis',['../classpython_1_1polynomial_1_1LagrangeBasis.html',1,'python::polynomial']]],
  ['lagrangedg_1630',['LagrangeDG',['../classpython_1_1element_1_1LagrangeDG.html',1,'python::element']]],
  ['lagrangefr_1631',['LagrangeFR',['../classpython_1_1element_1_1LagrangeFR.html',1,'python::element']]],
  ['lagrangeongausspoints_1632',['LagrangeOnGaussPoints',['../classpython_1_1expansion_1_1LagrangeOnGaussPoints.html',1,'python::expansion']]],
  ['lagrangeonlegendreroots_1633',['LagrangeOnLegendreRoots',['../classpython_1_1expansion_1_1LagrangeOnLegendreRoots.html',1,'python::expansion']]],
  ['lagrangeonlobattoroots_1634',['LagrangeOnLobattoRoots',['../classpython_1_1expansion_1_1LagrangeOnLobattoRoots.html',1,'python::expansion']]],
  ['lagrangeonuniformroots_1635',['LagrangeOnUniformRoots',['../classpython_1_1expansion_1_1LagrangeOnUniformRoots.html',1,'python::expansion']]],
  ['lax_1636',['Lax',['../classpython_1_1solver_1_1Lax.html',1,'python::solver']]],
  ['laxfriedrichs_1637',['LaxFriedrichs',['../classpython_1_1riemann_1_1LaxFriedrichs.html',1,'python::riemann']]],
  ['lazy_1638',['Lazy',['../classmini_1_1limiter_1_1weno_1_1Lazy.html',1,'mini::limiter::weno']]],
  ['legendre_1639',['Legendre',['../structmini_1_1integrator_1_1Legendre.html',1,'mini::integrator::Legendre&lt; T, N &gt;'],['../classpython_1_1expansion_1_1Legendre.html',1,'python.expansion.Legendre']]],
  ['legendredg_1640',['LegendreDG',['../classpython_1_1element_1_1LegendreDG.html',1,'python.element.LegendreDG'],['../classpython_1_1spatial_1_1LegendreDG.html',1,'python.spatial.LegendreDG']]],
  ['legendrefr_1641',['LegendreFR',['../classpython_1_1element_1_1LegendreFR.html',1,'python.element.LegendreFR'],['../classpython_1_1spatial_1_1LegendreFR.html',1,'python.spatial.LegendreFR']]],
  ['limiter_1642',['Limiter',['../classpython_1_1concept_1_1Limiter.html',1,'python::concept']]],
  ['line_1643',['Line',['../classmini_1_1basis_1_1lagrange_1_1Line.html',1,'mini::basis::lagrange::Line&lt; S, kDegree &gt;'],['../classmini_1_1integrator_1_1Line.html',1,'mini::integrator::Line&lt; S, D, Q &gt;']]],
  ['line_3c_20scalar_2c_20kdegreex_20_3e_1644',['Line&lt; Scalar, kDegreeX &gt;',['../classmini_1_1basis_1_1lagrange_1_1Line.html',1,'mini::basis::lagrange']]],
  ['line_3c_20scalar_2c_20kdegreey_20_3e_1645',['Line&lt; Scalar, kDegreeY &gt;',['../classmini_1_1basis_1_1lagrange_1_1Line.html',1,'mini::basis::lagrange']]],
  ['line_3c_20scalar_2c_20kdegreez_20_3e_1646',['Line&lt; Scalar, kDegreeZ &gt;',['../classmini_1_1basis_1_1lagrange_1_1Line.html',1,'mini::basis::lagrange']]],
  ['linear_1647',['Linear',['../classmini_1_1aircraft_1_1airfoil_1_1Linear.html',1,'mini::aircraft::airfoil::Linear&lt; Scalar &gt;'],['../classmini_1_1basis_1_1Linear.html',1,'mini::basis::Linear&lt; S, kDimensions, kDegrees &gt;'],['../classpython_1_1coordinate_1_1Linear.html',1,'python.coordinate.Linear'],['../classpython_1_1viscosity_1_1Linear.html',1,'python.viscosity.Linear']]],
  ['linear_3c_20scalar_2c_20kdimensions_2c_20kdegrees_20_3e_1648',['Linear&lt; Scalar, kDimensions, kDegrees &gt;',['../classmini_1_1basis_1_1Linear.html',1,'mini::basis']]],
  ['linearadvection_1649',['LinearAdvection',['../classpython_1_1equation_1_1LinearAdvection.html',1,'python.equation.LinearAdvection'],['../classpython_1_1riemann_1_1LinearAdvection.html',1,'python.riemann.LinearAdvection'],['../classpython_1_1wave__packet_1_1LinearAdvection.html',1,'python.wave_packet.LinearAdvection']]],
  ['linearadvectiondiffusion_1650',['LinearAdvectionDiffusion',['../classpython_1_1equation_1_1LinearAdvectionDiffusion.html',1,'python.equation.LinearAdvectionDiffusion'],['../classpython_1_1riemann_1_1LinearAdvectionDiffusion.html',1,'python.riemann.LinearAdvectionDiffusion']]],
  ['linearjumps_1651',['LinearJumps',['../classpython_1_1solver_1_1LinearJumps.html',1,'python::solver']]],
  ['linearsmooth_1652',['LinearSmooth',['../classpython_1_1solver_1_1LinearSmooth.html',1,'python::solver']]],
  ['linecache_1653',['LineCache',['../structmini_1_1spatial_1_1fr_1_1Lobatto_1_1LineCache.html',1,'mini::spatial::fr::Lobatto']]],
  ['liwanai2011_1654',['LiWanAi2011',['../classpython_1_1detector_1_1LiWanAi2011.html',1,'python::detector']]],
  ['liwanai2020_1655',['LiWanAi2020',['../classpython_1_1limiter_1_1LiWanAi2020.html',1,'python::limiter']]],
  ['liyanhui2022_1656',['LiYanHui2022',['../classpython_1_1detector_1_1LiYanHui2022.html',1,'python::detector']]],
  ['lobatto_1657',['Lobatto',['../structmini_1_1integrator_1_1Lobatto.html',1,'mini::integrator::Lobatto&lt; T, N &gt;'],['../classmini_1_1spatial_1_1dg_1_1Lobatto.html',1,'mini::spatial::dg::Lobatto&lt; P, R &gt;'],['../classmini_1_1spatial_1_1fr_1_1Lobatto.html',1,'mini::spatial::fr::Lobatto&lt; P, R &gt;']]]
];
